language: rust
rust:
  - stable
  - nightly
sudo: true
python: 3.7
addons:
    apt:
        packages:
            - libssl-dev
sudo: true
services:
  - xvfb
git:
    submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - sudo apt-get install -f -y libdbus-1-dev openssl
  - |
    # tarpaulin deps
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    fi
  - rustc -V
script:
  - cargo build
  - RUST_TEST_THREADS=1 cargo test -- --nocapture
  - |
    # tarpaulin deps
    if [[ "$TRAVIS_RUST_VERSION" != stable ]]; then
      cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --exclude-files src/main.rs tests/*;
    fi
