sequenceDiagram
    participant Alice_android
    participant Alice_pc
    participant RORI

    Alice_pc->>RORI:  send contact request
    Note right of RORI: Accept requets<br>(RORI is for anyone)

    Alice_pc->>RORI:  /register alice
    Note right of RORI: test to register alice
    RORI->>Alice_pc: ok
    Note left of Alice_pc: alice is registered<br>(alice@rori)
    Alice_pc->>RORI:  /add_device pc
    Note right of RORI: test to register<br>alice_pc
    RORI->>Alice_pc: ok
    Note left of Alice_pc: alice_pc is registered<br>(alice_pc@rori)



    Alice_android->>RORI:  send contact request
    Note right of RORI: Accept requets<br>(RORI is for anyone)
    Alice_android->>RORI:  /register alice
    Note right of RORI: test to register alice
    RORI->>Alice_android: err (already registered)
    Note left of Alice_android: alice_pc is still anonymous
    Alice_pc->>RORI:  /add_device pc
    Note right of RORI: ignore,<br>because anonymous
  
    Alice_pc->>RORI:  /link Alice_android (ring id)
    Note right of RORI: add new device for alice
    RORI->>Alice_pc: ok
    Note left of Alice_android: identified as alice
    Alice_android->>RORI:  /add_device android
    Note right of RORI: test to register<br>alice_android
    RORI->>Alice_android: ok
    Note left of Alice_android: alice_android is registered<br>(alice_android@rori)
